// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProductApi.Data;

#nullable disable

namespace ProductApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250307200151_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ProductApi.Models.Product", b =>
                {
                    b.Property<long>("ProductStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ProductStatusId"));

                    b.Property<string>("Barcode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DescriptionDomestic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("HasPersonalization")
                        .HasColumnType("boolean");

                    b.Property<bool>("HasVideo")
                        .HasColumnType("boolean");

                    b.Property<bool?>("IsDigital")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsElonkyFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsFeatured")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsTaxable")
                        .HasColumnType("boolean");

                    b.Property<string>("OtherCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonalizationDescription")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceDiscounted")
                        .HasColumnType("numeric");

                    b.Property<decimal>("PriceDiscountedDomestic")
                        .HasColumnType("numeric");

                    b.Property<string>("ProductStatusName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProductUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Stock")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TitleDomestic")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhenMade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("WhoMade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ProductStatusId");

                    b.ToTable("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
